version: '3.8'
services:

  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - shared:/var/www/html/public/:ro
      - .:/var/www/html/
    depends_on:
      injectable_db:
        condition: service_started
    networks:
      - app-intern

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - shared:/var/www/html/public/:ro
    depends_on:
      - php
      - injectable_db
    networks:
      - app-intern

  injectable_db:
    image: mysql:8.0
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-intern
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_USER=${MYSQL_ROOT_USER}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}

volumes:
  db-data:
  shared:

networks:
  app-intern:
    driver: bridge
    external: true
